 export  const products = [
    {type:"بروتين", name: "بياض بيض", weight: 300 },
    {type:"بروتين", name: "جبن قريش", weight: 200 },
    {type:"بروتين", name: "سمك سالمون", weight: 120 },
    {type:"بروتين", name: "سمك مكرونه", weight: 120 },
    {type:"بروتين", name: "سمك بلطي", weight: 120 },
    {type:"بروتين", name: "سردين", weight: 120 },
    {type:"بروتين", name: "سمك بوري", weight: 120 },
    {type:"بروتين", name: "سمك فيليه", weight: 120 },
    {type:"بروتين", name: "جمبري", weight: 100 },
    {type:"بروتين", name: "كبده", weight: 130 },
    {type:"بروتين", name: "تونه", weight: 100 },
    {type:"بروتين", name: "لحم صدور", weight: 120 },
    {type:"بروتين", name: "کیده دجاج", weight: 120 },
    {type:"بروتين", name: "لحم ارانب", weight: 100 },
    {type:"بروتين", name: "لحم احمر", weight: 120 },
    {type:"بروتين", name: "بيض كامل", weight: 250 },
    {type:"بروتين", name: "لحم وراك", weight: 100 },
    {type:"بروتين", name: "فيتا لايت", weight: 150 },
    {type:"بروتين", name: "فصوص رومي", weight: 120 },
    {type:"بروتين", name: "روس بيف", weight: 120 },
 
    
       { type: "كربوهيدرات", name: "كورن فلکس", weight: 55 },
      { type: "كربوهيدرات", name: "مكرونه شعريه", weight: 65 },
      { type: "كربوهيدرات", name: "رز", weight: 60 },
      { type: "كربوهيدرات", name: "برغل", weight: 60 },
      { type: "كربوهيدرات", name: "فريك", weight: 60 },
      { type: "كربوهيدرات", name: "فينو", weight: 90 },
      { type: "كربوهيدرات", name: "خبز شامي", weight: 85 },
      { type: "كربوهيدرات", name: "خبز بلدي", weight: 100 },
      { type: "كربوهيدرات", name: "كيزر", weight: 90 },
      { type: "كربوهيدرات", name: "توست ابيض", weight: 90 },
      { type: "كربوهيدرات", name: "توست اسمر", weight: 90 },
      { type: "كربوهيدرات", name: "کوز ذره مشوي", weight: 90 },
      { type: "كربوهيدرات", name: "بطاطس", weight: 260 },
      { type: "كربوهيدرات", name: "قلقاس", weight: 180 },
      { type: "كربوهيدرات", name: "بطاطا", weight: 260 },
      { type: "كربوهيدرات", name: "كينوا", weight: 60 },
      { type: "كربوهيدرات", name: "شوفان", weight: 60 },
      { type: "كربوهيدرات", name: "بقسماط", weight: 60 },
      { type: "كربوهيدرات", name: "بليله", weight: 60 },
      { type: "كربوهيدرات", name: "ذره فشار", weight: 65 },
      { type: "كربوهيدرات", name: "تورتيلا", weight: 80 },
    
        // المجموعة الأولى
  {  type: "دهون صحية", name: "المجموعة الأولى لوز", weight: 20 },
  {  type: "دهون صحية", name: "المجموعة الأولى کاجو", weight: 20 },
  {  type: "دهون صحية", name: "المجموعة الأولى بندق", weight: 20 },
  {  type: "دهون صحية", name: "المجموعة الأولى فول سوداني", weight: 20 },
  {  type: "دهون صحية", name: "المجموعة الأولى بيكان", weight: 20 },
  {  type: "دهون صحية", name: "المجموعة الأولى فصدق", weight: 20 },
  {  type: "دهون صحية", name: "المجموعة الأولى زيت زيتون بالمعلقة وليس بالجرام", weight: 3},
  {  type: "دهون صحية", name: "المجموعة الأولى زيتون اسود", weight: 15 },
  {  type: "دهون صحية", name: "المجموعة الأولى افوكادو", weight: 60 },

  // المجموعة الثانية
  {  type: "دهون صحية", name: " المجموعة الثانية عين جمل", weight: 20 },
  {  type: "دهون صحية", name: " المجموعة الثانية زيت نباتي بالمعلقة وليس بالجرام", weight: 3},
  {  type: "دهون صحية", name: " المجموعة الثانية بذور کتان", weight: 20 },
  {  type: "دهون صحية", name: " المجموعة الثانية بذور شيا", weight: 20 },

  // المجموعة الثالثة
  {  type: "دهون صحية", name: "المجموعة الثالثة زبد طبيعي", weight: 15 },
  {  type: "دهون صحية", name: "المجموعة الثالثة زبد صناعي", weight: 15 },
  {  type: "دهون صحية", name: "المجموعة الثالثة زيت جوز هند بالمعلقة وليس بالجرام", weight: 3},

  { type: "فواكه", name: "بطيخ", weight: 200 },
  { type: "فواكه", name: "تفاح", weight: 100 },
  { type: "فواكه", name: "کماری", weight: 100 },
  { type: "فواكه", name: "خرنگش", weight: 85 },
  { type: "فواكه", name: "يوسفي", weight: 100 },
  { type: "فواكه", name: "تين شوكي", weight: 100 },
  { type: "فواكه", name: "توت", weight: 85 },
  { type: "فواكه", name: "کاکا", weight: 65 },
  { type: "فواكه", name: "تین برشومي", weight: 85 },
  { type: "فواكه", name: "برتقال", weight: 100 },
  { type: "فواكه", name: "فراوله", weight: 200 },
  { type: "فواكه", name: "مانجا", weight: 100 },
  { type: "فواكه", name: "كيوي", weight: 100 },
  { type: "فواكه", name: "اناناس", weight: 100 },
  { type: "فواكه", name: "عنب", weight: 80 },
  { type: "فواكه", name: "برقوق", weight: 85 },
  { type: "فواكه", name: "جوافه", weight: 100 },
  { type: "فواكه", name: "شمام", weight: 200 },
  { type: "فواكه", name: "كانتلوب", weight: 200 },
  { type: "فواكه", name: "خوخ", weight: 100 },
  { type: "فواكه", name: "رمان", weight: 85 },
  { type: "فواكه", name: "مشمش", weight: 100 },
  { type: "فواكه", name: "بلح", weight: 20 },
  { type: "فواكه", name: "موز", weight: 60 },
  { type: "فواكه مجففة", name: "زبيب", weight: 20 },
  { type: "فواكه مجففة", name: "قراصيا", weight: 20 },
  { type: "فواكه مجففة", name: "تين", weight: 25 },
  { type: "فواكه مجففة", name: "مشمش مجفف", weight: 20 },

  { type: "منتجات ألبان", name: "لبن بودر", weight: 30 },
  { type: "منتجات ألبان", name: "لبن كامل الدسم", weight: 240 },
  { type: "منتجات ألبان", name: "زبادي كامل الدسم", weight: 240 },
  { type: "منتجات ألبان", name: "لبن خالي الدسم", weight: 240 },

  { type: "بقوليات", name: "حمص", weight: 25 },
  { type: "بقوليات", name: "عدس", weight: 30 },
  { type: "بقوليات", name: "فاصولياء حمراء", weight: 30 },
  { type: "بقوليات", name: "فاصولياء بيضاء", weight: 30 },
  { type: "بقوليات", name: "لوبيا", weight: 30 },
  { type: "بقوليات", name: "فول", weight: 30 },
  { type: "بقوليات", name: "ترمس", weight: 50 },
  { type: "بقوليات", name: "بسله", weight: 30 },
    
  { type: "خضروات", name: "فلفل الوان", weight: 50 },
  { type: "خضروات", name: "خس", weight: 100 },
  { type: "خضروات", name: "خیار", weight: 100 },
  { type: "خضروات", name: "کوسه", weight: 50 },
  { type: "خضروات", name: "بامیه", weight: 50 },
  { type: "خضروات", name: "جرجير", weight: 100 },
  { type: "خضروات", name: "باذنجان", weight: 150 },
  { type: "خضروات", name: "فاصوليا خضرا", weight: 50 },
  { type: "خضروات", name: "جزر", weight: 50 },
  { type: "خضروات", name: "قرنبيط", weight: 100 },
  { type: "خضروات", name: "بنجر", weight: 50 },
  { type: "خضروات", name: "طماطم", weight: 100 },
  { type: "خضروات", name: "مشروم", weight: 100 },
  { type: "خضروات", name: "خرشوف", weight: 50 },
  { type: "خضروات", name: "بروكلي", weight: 50 },
  { type: "خضروات", name: "ملوخيه", weight: 50 },
  { type: "خضروات", name: "سبانخ", weight: 100 },
  ];


  